### ISSUE TITLE
Fix your privacy.

### ISSUE THREAD

**Issue by violetwtf** [GamingGeek/Fire#16]
The following is demanded on behalf of myself and others:
* Allow data to be requested by users
* Require an opt-in for data collection
* Display a clear privacy policy

Fire, and by connection you, are in violation of several U.S. state and federal laws, as well as GDPR. You are also violating copyright law, as the copyright of Discord messages belongs to their owners and Discord per ToS.

Failure to comply will result in contacting Discord Trust & Safety, as you're in direct violation of law and terms of service.

**Comment by Nystrex** [comment]
did i ask?

**Comment by AmpTheDev** [comment]
😐

**Comment by SystemlessDev** [comment]
First off fire is not based in USA so your laws aren't valid for us.

Show us the sections of GDPR that we are violating plus the features that allegedly violates it.

Fire doesn't store any data (other than user provided data like warns, mutes etc.) over longer time so there is nothing to opt out of and also nothing to download.

You also don't have to be in a discord with fire. You are allowed to either kick fire from your server(s) or leave the server(s) that has the bot.

Feel free to contact discord trust and safety if you believe that fire is breaking any laws and/or discord TOS.

Thank you
Systemless // Vegard

**Comment by GamingGeek** [comment]
@Systemless has basically covered everything but if you want my words, continue reading

> Allow data to be requested by users

Do you want your data? I can give it to you if you want. (Although, there's not much as I don't store much)

> Require an opt-in for data collection

I don't collect much data and the data I do collect is for features of the bot to function
![image](https://user-images.githubusercontent.com/29981918/75456451-74445300-5972-11ea-9a19-42fd085f28b5.png)

> Display a clear privacy policy

Noted.

> Fire, and by connection you, are in violation of several U.S. state and federal laws

Don't remember Fire being based in the U.S but Ok

> as well as GDPR

Would've helped if you actually provided the sections (as their names or the text itself) because without it your point is invalid. That's like saying `He broke the law` but not saying what law he broke

> You are also violating copyright law, as the copyright of Discord messages belongs to their owners and Discord per ToS.

Messages are only stored in memory and any messages that are stored are used for features of the bot such as logging, events and *your favorite* snipes. Fire **does not** and **will never** save messages in persisted storage. 
You can disable logging and snipe commands by using the following commands;
```
$logs mod
$logs action
$command snipe
$command esnipe
```
Disabling the snipe commands does not prevent the messages from being stored as moderators can still use disabled commands.

> Failure to comply will result in contacting Discord Trust & Safety, as you're in direct violation of law and terms of service.
**Go on, knock yourself out**
If Discord were to do anything about features such as logging/message snipes, they would've done so already to the many other bots that have these features, such as Dyno's logging (remember, Dyno is a Discord Partner) and Dank Member's snipe command.

**Comment by Nekiono** [comment]
Side note;

as per Discord ToS you do own your content, but basically grant Discord a wildcard license for them - this includes displaying them in their API.

(also the obligatory noone here is a lawyer / this isn't legal advice)

**Comment by violetwtf** [comment]
I'm so sorry.
